/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/index`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Register`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/homepage/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/homepage/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/homepage/Tasks`; params?: Router.UnknownInputParams; } | { pathname: `/homepage/Analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(homepage)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(homepage)'}/Tasks` | `/Tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(homepage)'}/Analytics` | `/Analytics`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/index`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/homepage/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `/homepage/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/homepage/Tasks`; params?: Router.UnknownOutputParams; } | { pathname: `/homepage/Analytics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(homepage)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(homepage)'}/Tasks` | `/Tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Login` | `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(homepage)'}/Analytics` | `/Analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/auth/index${`?${string}` | `#${string}` | ''}` | `/auth/Register${`?${string}` | `#${string}` | ''}` | `/auth/Login${`?${string}` | `#${string}` | ''}` | `/homepage/tasks${`?${string}` | `#${string}` | ''}` | `/homepage/Profile${`?${string}` | `#${string}` | ''}` | `/homepage/Tasks${`?${string}` | `#${string}` | ''}` | `/homepage/Analytics${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Register${`?${string}` | `#${string}` | ''}` | `/Register${`?${string}` | `#${string}` | ''}` | `${'/(homepage)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `${'/(homepage)'}/Tasks${`?${string}` | `#${string}` | ''}` | `/Tasks${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Login${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `${'/(homepage)'}/Analytics${`?${string}` | `#${string}` | ''}` | `/Analytics${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/index`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Register`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/homepage/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/homepage/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/homepage/Tasks`; params?: Router.UnknownInputParams; } | { pathname: `/homepage/Analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(homepage)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(homepage)'}/Tasks` | `/Tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(homepage)'}/Analytics` | `/Analytics`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
